apiVersion: 1

datasources:
  - name: Forklift API
    type: grafana-simple-json-datasource
    access: proxy
    url: http://host.docker.internal:5005/api/grafana
    isDefault: true
    uid: forklift-api
    jsonData:
      keepCookies: []
    secureJsonData: {}

